README.md

I had to dive into the code to understand how to use it, hopefully these `README.md` changes make it a bit more clear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alexbosworth/balanceofsatoshis/1)

Make README a little bit more clear

---

swaps/rebalance.js

Closes https://github.com/alexbosworth/balanceofsatoshis/issues/33

chore: add rebalance response

---

README.md

The sample does not make sense. It's asking for the balance for the same node twice.

Fix logic in README sample shell command

---

display/describe_route.js

This fill fix a failure in `bos probe`

Fix ReferenceError: Strig is not defined

---

README.md

changed ip to be port.
this was bugging me :)

typo: "ip" to "port" in README

---

bos
peers/channels_from_arguments.js
peers/open_channels.js

added a new flag called `--closing-address` to `bos open` command that takes in multiple closing addresses.

Add closing address to bos open

---

bos
package-lock.json
package.json
services/initiate_balanced_channel.js
services/open_balanced_channel.js
telegram/start_telegram_bot.js

Added a flag to open-balanced-channel command called `coop-close-address`.
added condition so that only the initiator can pass a closing address.
added address validation check
Modified files 
`bos`
`initiate_balanced_channel`
`open_balanced_channel`

Add coop-close-address to open-balanced-channel

---

balances/get_accounting_report.js
bos

Added a table that shows total amount to bos accounting outputs.
files changed
get_accounting_report.js
bos

adding total amounts table to bos accounting

---

telegram/interaction.json
telegram/start_telegram_bot.js

switching from v1 to v2 markdown.
In escaping I removed `*` since that isn't necessary.

switch from v1 to v2 markdown

---

bos
services/advertise.js

Add a budget flag and a budget amount in the send function.
Files changed:
services/advertise.js
bos
https://github.com/alexbosworth/balanceofsatoshis/issues/155

add budget to advertise command

---

bos
services/advertise.js

Adding min and max hops flags to bos advertise comand.
Files changed:
bos
services/advertise.js

add min and max hops flags for advertise command

---

telegram/start_telegram_bot.js

Change the location of node down alert. 
Files changed: telegram/start_telegram_bot.js
This method works but maybe there could be better ways of handling it, the downsides I see so far is, there might be a 3min delay in sending the disconnect notification because of 
`const restartDelayMs = 1000 * 60 * 3;`

move node disconnect alert

---

bos
package-lock.json
package.json
telegram/connect_to_telegram.js

Related to #219 
Needs the merge of this pull request alexbosworth/ln-telegram#9

added option to receive amounts from the telegram bot in sats

---

services/advertise.js

Skips entire graph download when advertising to peers and gets channels instead when maxhops=0
Files changed: services/advertise.js

skip graph download for peer advertising

---

bos
lnurl/pay.js

Added `avoid`, `max-paths` and `out` flags to lnurl command.
Files changed:
bos
lnurl/pay.js

[lnurl] Add avoid, max-paths and out flags

---

bos
commands/constants.json
lnurl/index.js
lnurl/manage_lnurl.js
lnurl/pay.js
lnurl/withdraw.js

Added a new function to withdraw from lnurl.
Link to test: (does not actually let you withdraw)
https://lnurl.fiatjaf.com/
WithdrawRequest Spec:
https://github.com/fiatjaf/lnurl-rfc/blob/luds/03.md
Files changed:
bos
commands/constants.json
lnurl/index.js
New Files:
lnurl/manage_lnurl.js
lnurl/withdraw.js

[lnurl]- add withdraw using lnurl

---

bos
commands/constants.json
lnurl/auth.js
lnurl/manage_lnurl.js

Added a new lnurl function to authenticate using lnurl
Files changed:
bos
commands/constants.json
lnurl/manage_lnurl.js
New File:
lnurl/auth.js
Testing: 
https://lnurl.fiatjaf.com/
Testing with a real website if needed:
https://stacker.news/

[lnurl]-added lnurl auth

---

bos
lnd/gateway.js

Added minutes and nospend flags to bos gateway command.
Files changed:
bos
lnd/gateway.js

[gateway]: Add minutes and nospend flag

---

bos
routing/get_fees_chart.js
routing/get_forwards.js

Added start and end flags for chart-fees-earned.
Files changed:
bos
routing/get_fees_chart.js
routing/get_forwards.js

Add start-end flags for chart-fees-earned

---

telegram/get_lnds.js
telegram/run_telegram_bot.js
telegram/start_telegram_bot.js

https://github.com/alexbosworth/balanceofsatoshis/issues/350
Uses a fresh lnd connection every time you run a command on telegram.
Files changed:
telegram/run_telegram_bot.js
telegram/start_telegram_bot.js
New File:
telegram/get_lnds.js

[telegram]: Use fresh connection for commands

---

README.md

Adds 'docker pulls' badge to readme

---

bos
offchain/create_invoice.js
offchain/sign_payment_request.js

Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>
Closes #435 
Added expiry control to invoice command.
Files changed:
offchain/create_invoice.js
offchain/sign_payment_request.js

add expiry control to invoice command

---

bos
chain/fund_transaction.js

Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>
Closes: #477
Files changed:
bos
chain/fund_transaction

[fund]: Add broadcast flag to bos fund command

---

bos
peers/open_channels.js

Add check if node supports anchor channels in the open command to accidentally not open to nodes that don't support anchors and cry later.

[open]: add check for anchor channels for open command

---

bos
peers/channels_from_arguments.js
peers/open_channels.js
test/integration/test_open_channels.js
test/integration/test_taproot_channels.js
test/integration/test_trusted_channels.js

Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>

[open]: Add taproot channels support to bos open

---

bos
lsp/lsps1_client.js
lsp/process_order.js

implement suggested fixes to lsps1
